---
title: "Billiards and Tilts Analysis Notebook"
author: "Shanaathanan Modchalingam"
output: 
  html_notebook:
    toc: true
    toc_float: true
    number_sections: true
    df_print: paged
    code_folding: hide
---


```{r setup, include=FALSE, warning=FALSE}
rm(list = ls()) # clean environment

source("../src/helper_funcs.R")
source("../scripts/figure_funcs.R")
library(data.table)
library(tidyverse)
library(ggbeeswarm)
library(ez) # for ANOVAs
library(effectsize) # for eta-squared

library(furrr)
plan(multisession)

options(dplyr.summarise.inform = FALSE)

# vars
omnibus_path <- "../data/processed/omnibus/omnibus_raw.csv"

# convert the above into a list
pallete_list <- c(
  "rot30_cued_tilt" = "#d40000",
  "rot30_uncued" = "#f9982c",
  "accel_cued_tilt" = "#07509b",
  "accel_uncued" = "#5fb696",
  "curved_cued_tilt" = "#2b5747",
  "rot15_cued_tilt" = "#770202",
  "rot15_uncued" = "#a76315",
  "none" = "#f9982c",
  "half_anim" = "#5fb696",
  "full_anim" = "#07509b",
  "wait" = "#a76315"
)

num_exps <- 7
save_plots <- FALSE
```



## Load all of the throw data
```{r}
# Note: this notebook right now REQUIRES that the analysis notebook be run to
# make the fits, or that the data folder contains the fits

# load omnibus dataframe
omnibus_df <- read_delim("../data/processed/omnibus/omnibus_raw.csv",
  delim = ",",
  col_types = cols(
    .default = col_double(),
    type = col_factor(),
    ppid = col_factor(),
    exp_label = col_factor(),
    experiment = col_factor(),
    hand = col_factor(),
    camera_tilt = col_factor(),
    surface_tilt = col_factor(),
    target = col_factor(),
    test_type = col_factor(),
    prior_anim = col_factor(),
    baseline_block = col_factor(),
    task_type = col_factor(),
    surface = col_factor(),
    anim_type = col_factor()
  )
) %>% # filter out practice blocks
  filter(block_num > 4)

# load exponential decay fits
init_learning_rates <- read_csv(
  "../data/processed/learning_rate_df.csv",
  col_types = cols(
    .default = col_double(),
    experiment = col_factor(),
    test_type = col_factor()
  )
)

init_learning_rates_3par <- read_csv(
  "../data/processed/learning_rate_df_3par.csv",
  col_types = cols(
    .default = col_double(),
    experiment = col_factor(),
    test_type = col_factor()
  )
)

anim_learning_rates <- read_csv(
  "../data/processed/learning_rate_df_anim.csv",
  col_types = cols(
    .default = col_double(),
    ppid = col_factor(),
    experiment = col_factor()
  )
)
```
# Figure 1: Setup
# Figure 2: Learning Curves

```{r}
# filter out data
data_per_ppt <- omnibus_df %>%
  filter(
    experiment %in% c(
      "accel_uncued", "accel_cued_tilt",
      "rot30_uncued", "rot30_cued_tilt"
    ),
    trial_num >= 214
  ) %>%
  mutate(
    trial_num = ifelse(
      trial_num >= 335,
      trial_num - 1,
      trial_num
    )
  )

# make per_group df
data_per_group <- data_per_ppt %>%
  group_by(experiment, test_type, trial_num) %>%
  summarise(
    mean_deviation = mean(throw_deviation),
    ci_deviation = vector_confint(throw_deviation),
    n = n(),
    .groups = "drop"
  )

# set up plot
p <- data_per_group %>%
  ggplot(
    aes(
      x = trial_num - 213,
      y = mean_deviation,
      colour = experiment
    )
  ) +
  theme_classic() +
  theme(legend.position = "none") +
  labs(
    x = "Trial Number",
    y = "Throw Angle (°)"
  )

# add horizontal lines
p <- p +
  geom_hline(
    yintercept = c(0, -30), linewidth = 0.4,
    colour = "#CCCCCC", linetype = "solid"
  ) +
  geom_hline(
    yintercept = c(-15), linewidth = 0.4,
    colour = "#CCCCCC", linetype = "dashed"
  )

p <- p +
  scale_y_continuous(
    # limits = c(-35, 5),
    breaks = c(0, -15, -30),
    labels = c(0, -15, -30)
  ) +
  scale_x_continuous(
    # limits = c(0, 160),
    breaks = c(0, 40, 80, 120, 160),
    labels = c(0, 40, 80, 120, 160)
  )

# set font size to 11
p <- p +
  theme(text = element_text(size = 11))

# add confidence intervals and data points
p <- p + geom_ribbon(
  aes(
    ymin = mean_deviation - ci_deviation,
    ymax = mean_deviation + ci_deviation,
    fill = experiment
  ),
  colour = NA, alpha = 0.3
) + geom_line()

# set colour palette
p <- p +
  scale_colour_manual(values = pallete_list) +
  scale_fill_manual(values = pallete_list)

# save
if (save_plots) {
  ggsave(
    p,
    filename = "../plots/paper_figs/sr_30_training.pdf", device = "pdf",
    height = 4, width = 6
  )
}

p
```

